### ISSUE TITLE
translationWords missing content

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#24] opened 2016-02-24 16:23 UTC
@RRohrssen 
This was received on Slack #helpdesk on 2-23-16 
Eric Steggerda [4:16 AM] 
@channel: My translator for Russian Bible Words in tS reports:  "Some sentences were not full.

For example, A - "Apollos" - Apollos was a Jew from the city of Alexandria in Greece, ect.. Paul emphasized how he...    The sentence is not finished.

I found many unfinished articles. "

Upon further discovery it was found that next in the sentence is '(Paul).'
I also looked at further terms and noticed that in tS-Desktop that Andrew is missing content starting with the ( character.

This is a bug.?

**Comment by ChrisJarka** [comment] 2016-02-24 16:25
This was received on Slack Helpdesk 2-24-16

Eric Steggerda [10:19 AM] 
@christinej: here is a list of stuff for other errors in upload: Abiathar (english phrases mixed with spanish? sentences)
Absalom (no full stop at the end of the article - I'm not sure if the idea is finished)
Ahaziah (no full stop...)
Andrew
Apollos
Barnabas
Berea
Bethel
Boaz (no full stop...)
Damascus (no full stop...)
Ephesus
Euphrates (no full stop...)
Eve (no full stop...)
God (the phrase before "Translation Suggestions")
God the Father (the phrase before "Translation Suggestions")
Habakkuk (no full stop...)
Herod the Great
Herodias
Holy One
I, Yahweh; me Yahweh
Iconium (no full stop...)
Jesus
John (the apostle)
Jotham (no full stop...)
Judah, kindom of Judah
Judaism

[10:20] 
there is more I am sure, but this is just from A to J

**Comment by ChrisJarka** [comment] 2016-02-24 16:28
Looking at my copy of tS-D v3
Abiathar does have Spanish in the English definition.
Ahaziah has He reigned for one year    And then on D43 there is "He reigned for one year (841 BC)"

**Comment by jag3773** [comment] 2016-02-24 19:54
Duplicate of https://github.com/unfoldingWord-dev/ts-desktop/issues/378 ?

**Comment by ChrisJarka** [comment] 2016-03-01 11:32
This is the same issue as for https://github.com/unfoldingWord-dev/ts-desktop/issues/318 @cdwhitfield73

**Comment by jag3773** [comment] 2016-03-08 21:15
Verified as dup of https://github.com/unfoldingWord-dev/ts-desktop/issues/378 by @ChrisJarka and myself.

**Closed as completed by jag3773** 2016-03-08 21:15 UTC
