### ISSUE TITLE
More consistent/valuable feedback during i/o operations

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#87] opened 2016-04-08 18:43 UTC
We show the user a progress bar during backup, restore, publish, export, and print processes. During a project load process we just display the "Loading project, please wait..." modal. It would be nice to see the progress bar during the project load process as well, both for consistency as well as loading a large project on a slow machine can take a fair amount of time when the user is left wondering if it's working or frozen. There are also times when the progress bar stops for several seconds. It would be nice if that could be fixed as well.

**Comment by cdwhitfield73** [comment] 2016-04-08 18:48
This sounds like a duplicate of #86, and is already incorporated into the current code (not merged into develop yet) in desktop

**Comment by cdwhitfield73** [comment] 2016-05-17 21:08
This is complete in Desktop.

**Closed as completed** 2016-09-02 21:17 UTC
Labels: Resolved???
